name: raghad_s_razeen
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
   
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.4
  intl: ^0.18.0

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4

  cloud_firestore: ^4.15.5


  email_validator: ^2.0.1
  font_awesome_flutter: ^10.7.0
  maze: ^3.0.0
  audioplayers: ^6.0.0
  just_audio: ^0.9.37
  image: ^4.1.7
  ar_flutter_plugin: ^0.7.3 
  arcore_flutter_plugin: ^0.1.0
  video_player: ^2.8.3
  flick_video_player: ^0.7.0
  

dev_dependencies: 

  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/ 
    - assets/true.wav
    - assets/false.wav
    - assets/firstaudio1.mp3
    - assets/safeplaceStory.mp4
    - assets/badHelp.mp3
    - assets/bring_tissue.mp3
    - assets/bring_water.mp3
    - assets/Bring.mp3
    - assets/classify.mp3
    - assets/How_Changes.mp3
    - assets/How_Order.mp3
    - assets/How_Quite.mp3
    - assets/How_Safe.mp3
    - assets/How_Talk.mp3
    - assets/Im_Sorry.mp3
    - assets/Im_Sorry.mp3
    - assets/mazeQuizQuestion.mp3
    - assets/Newspaper.mp3
    - assets/noGift.mp3
    - assets/notMyfault.mp3
    - assets/pleaseHelp.mp3
    - assets/Q_change.mp3
    - assets/Q_Order.mp3
    - assets/SafeplaceQuizAudio.mp3
    - assets/thankyouGift.mp3
    - assets/whatWord.mp3
    - assets/maze_water.mp3
    - assets/puzzle.mp3

   
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Baloo Chettan 2
    
      fonts: 
        - asset: assets/fonts/BalooChettan2SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BalooChettan2Regular.ttf
          weight: 400
